### PR TITLE
Handle non-strings in JSON

### LINKED ISSUE #368: AttributeError in Jinja2 call
I'm fairly certain this is a Jinja2 bug (submitted [here](https://github.com/mitsuhiko/jinja2/issues/396)), but the ultimate impact is that `cookiecutter==0.9.0` is broken for me (on Python 2 and Python 3).

Steps to reproduce:

     $ pip2 install cookiecutter==0.9.0 && cookiecutter gh:jacebrowning/template-python --no-input

```
Traceback (most recent call last):
  File "/opt/boxen/homebrew/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.9.0', 'console_scripts', 'cookiecutter')()
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/cookiecutter/main.py", line 169, in main
    cookiecutter(args.input_dir, args.checkout, args.no_input)
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/cookiecutter/main.py", line 100, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/cookiecutter/prompt.py", line 29, in prompt_for_config
    val = env.from_string(raw).render(cookiecutter=cookiecutter_dict)
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/jinja2/environment.py", line 841, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/jinja2/environment.py", line 542, in compile
    source = optimize(source, self)
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/jinja2/optimizer.py", line 27, in optimize
    return optimizer.visit(node)
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/jinja2/visitor.py", line 39, in visit
    return self.generic_visit(node, *args, **kwargs)
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/jinja2/visitor.py", line 59, in generic_visit
    for field, old_value in node.iter_fields():
AttributeError: 'int' object has no attribute 'iter_fields'
```

This still works with `cookiecutter==0.8.0`:

     $ pip2 install cookiecutter==0.8.0 && cookiecutter gh:jacebrowning/template-python --no-input

My environment:

* OS X 10.10.1
* Python 2.7.9
* pip 1.5.6

### PR DESCRIPTION
**Pull request by jacebrowning**
Fixes #368

### CODE REVIEW

**Comment by jacebrowning** [comment]
@michaeljoseph I think the build failures in `py27` and `pypy` are outside of my changes.

**Comment by pydanny** [comment]
Ah yes, the dreaded unicode exceptions in 2.7. After work I'll take a look at it.

File: cookiecutter/prompt.py [hunk 1]
```diff
@@ -26,7 +26,7 @@ def prompt_for_config(context, no_input=False):
     env = Environment()
 
     for key, raw in iteritems(context['cookiecutter']):
-        val = env.from_string(raw).render(cookiecutter=cookiecutter_dict)
+        val = env.from_string(str(raw)).render(cookiecutter=cookiecutter_dict)
```
Comment (michaeljoseph) [inline cookiecutter/prompt.py]: How about an `isinstance` check first?
Unfortunately, it's a little bit more fiddly to be py2 and py3 compatible- I suggest adding something from [this SO question](http://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility) to `compat.py`

**Comment by jacebrowning** [comment]
@michaeljoseph @pydanny It's passing with `py27` now. There was a "bad md5 hash" while installing dependencies for `pypy`? https://travis-ci.org/audreyr/cookiecutter/jobs/47559696#L123

**Comment by jacebrowning** [comment]
`$ tox -e pypy` passed for me locally.

File: cookiecutter/compat.py [hunk 2]
```diff
@@ -131,4 +131,18 @@ def _access_check(fn, mode):
...
+
+    def isstr(s):
+        """Determine if an object is a string in Python 2."""
+        return isinstance(s, basestring)
+
+except NameError:
+
+    def isstr(s):
+        """Determine if an object is a string in Python 3."""
+        return isinstance(s, str)
```
Comment (michaeljoseph) [inline cookiecutter/compat.py]: @jacebrowning Since this module already knows the version of python, what do you think of:
```python
def is_str(s):
    return isinstance(s, str if PY3 else basestring)
```
?

Comment (jacebrowning) [inline cookiecutter/compat.py]: @michaeljoseph good call.

**Comment by jacebrowning** [comment]
Let me know if that's not your preferred method for disabling a `flake8` warning.

File: cookiecutter/compat.py [hunk 3]
```diff
@@ -131,4 +131,10 @@ def _access_check(fn, mode):
                         return name
         return None
 
+
+def isstr(obj):
```
Comment (michaeljoseph) [inline cookiecutter/compat.py]: `is_string` is a bit more readable?

File: cookiecutter/compat.py [hunk 4]
```diff
@@ -131,4 +131,10 @@ def _access_check(fn, mode):
...
+    """Determine if an object is a string."""
+    return isinstance(obj, str if PY3 else basestring)  # NOQA
```
Comment (michaeljoseph) [inline cookiecutter/compat.py]: What `flake8` warning does this cause?

Comment (jacebrowning) [inline cookiecutter/compat.py]: With `flake8` installed in a Python 3 virtualenv:

`cookiecutter/compat.py:137:44: F821 undefined name 'basestring'`

Comment (michaeljoseph) [inline cookiecutter/compat.py]: Travis runs `flake8` in a Python 2 venv, so I think the comment can go.

**Comment by jacebrowning** [comment]
@michaeljoseph Anything else?

**Comment by michaeljoseph** [comment]
@jacebrowning looks good!
:cake: :+1: 
cc: @pydanny

**Comment by pydanny** [comment]
:+1:

**Comment by pydanny** [comment]
Just released on PyPI: https://pypi.python.org/pypi/cookiecutter/0.9.1

Please test manually! I need a confirmation it's all good before I announce it publicly.

**Comment by jacebrowning** [comment]
@pydanny Passes locally and on Travis: https://travis-ci.org/jacebrowning/template-python/builds/47704251

**Comment by pydanny** [comment]
Thanks @jacebrowning. Excellent! :birthday:
